1. 

(X_train=80%)
(X_test=20%)

A partir del archivo "iris.csv" que se corresponde con datos relacionados con tres tipos de plantas (el target es el tipo de planta):

- Mediante regresión logística, predice qué planta se corresponde con los ejemplos: [[15.7,2.8,9.5,0.1]] y [[1.7,3.8,4.5,11.3]]
- ¿Qué acierto tiene tu modelo? (score)
- Utiliza un conjunto de test con el 40% de los datos: ¿cambian los resultados anteriores? ¿por qué?
- Elimina la clase "Virginica" de tus datos. Repite el proceso anterior, ¿cambian los resultados?
- ¿Consideras la regresión logística un buen algoritmo para estos datos? ¿por qué?

In [1]:
import pandas as pd 
import numpy as np 
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
data = pd.read_csv("../data/iris.csv")
data

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
label= preprocessing.LabelEncoder()
variety= label.fit_transform(data.variety)
variety

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
y= np.array(variety)
y.shape

(150,)

In [5]:
X= np.array(data.drop(["variety"], axis= 1))
X.shape

(150, 4)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [7]:
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [8]:
y_predict= model.predict(X_test)
y_predict

array([2, 2, 2, 1, 1, 1, 0, 2, 2, 0, 1, 2, 2, 0, 0, 1, 1, 1, 2, 2, 2, 0,
       1, 1, 2, 1, 0, 0, 1, 1])

¿Qué acierto tiene tu modelo? (score)

In [10]:
model.score(X_test, y_test)

1.0

In [13]:
y_test.shape

(30,)

In [9]:
new1= model.predict([[15.7,2.8,9.5,0.1]])
new1

array([2])

In [11]:
new2= model.predict([[1.7,3.8,4.5,11.3]])
new2

array([2])

Utiliza un conjunto de test con el 40% de los datos: ¿cambian los resultados anteriores? ¿por qué?

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.60)

In [16]:
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [17]:
y_predict= model.predict(X_test)
y_predict

array([0, 0, 0, 2, 1, 2, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 2, 2,
       1, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0, 0, 2, 1, 0, 1, 2, 2, 0, 0, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 2, 1, 1, 0, 0, 1, 2, 2, 0, 0, 2, 1, 0, 2, 1, 2, 0, 2, 1, 2,
       1, 1])

In [18]:
model.score(X_test, y_test)

0.9555555555555556

In [19]:
new1= model.predict([[15.7,2.8,9.5,0.1]])
new1

array([2])

In [20]:
new2= model.predict([[1.7,3.8,4.5,11.3]])
new2

array([2])

Elimina la clase "Virginica" de tus datos. Repite el proceso anterior, ¿cambian los resultados?

In [22]:
df= data[data.variety != "Virginica"]
df

sepal.length  sepal.width  petal.length  petal.width     variety
0            5.1          3.5           1.4          0.2      Setosa
1            4.9          3.0           1.4          0.2      Setosa
2            4.7          3.2           1.3          0.2      Setosa
3            4.6          3.1           1.5          0.2      Setosa
4            5.0          3.6           1.4          0.2      Setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  Versicolor
96           5.7          2.9           4.2          1.3  Versicolor
97           6.2          2.9           4.3          1.3  Versicolor
98           5.1          2.5           3.0          1.1  Versicolor
99           5.7          2.8           4.1          1.3  Versicolor

[100 rows x 5 columns]

In [23]:
X= np.array(df.drop(["variety"], axis=1))
X.shape

(100, 4)

In [24]:
label = preprocessing.LabelEncoder()
variety = label.fit_transform(df.variety)
y= np.array(variety)
y.shape

(100,)

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
model = KNeighborsClassifier(n_neighbors=8)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Score k=8:", model.score(X_test, y_test))

Score k=8: 1.0


In [26]:
new1= model.predict([[15.7,2.8,9.5,0.1]])
new1

array([1])

In [27]:
new2= model.predict([[1.7,3.8,4.5,11.3]])
new2

array([1])