### 1. 

En el archivo "logistic_regression_df_class" hemos visto un ejemplo multiclase. Elimina del dataframe todas las filas que se correspondan con la clase valor "1".

Ahora, realiza el ejercicio con el nuevo dataframe:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline
dataframe = pd.read_csv("../data/usuarios_win_mac_lin.csv")
dataframe.head()

duracion  paginas  acciones  valor  clase
0       7.0        2         4      8      2
1      21.0        2         6      6      2
2      57.0        2         4      4      2
3     101.0        3         6     12      2
4     109.0        2         6     12      2

In [10]:
clase1= dataframe.loc[dataframe["clase"]== 1]
dataframe

duracion  paginas  acciones  valor  clase
0         7.0        2         4      8      2
1        21.0        2         6      6      2
2        57.0        2         4      4      2
3       101.0        3         6     12      2
4       109.0        2         6     12      2
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[170 rows x 5 columns]

In [13]:
df= dataframe[dataframe.clase != 1]
df

duracion  paginas  acciones  valor  clase
0         7.0        2         4      8      2
1        21.0        2         6      6      2
2        57.0        2         4      4      2
3       101.0        3         6     12      2
4       109.0        2         6     12      2
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[130 rows x 5 columns]

In [49]:
X = np.array(df.drop(['duracion'], axis=1))
y = np.array(df['clase'])
X.shape

(130, 4)

In [27]:
#No es necesario para este ejercicio, lo que se coge es la columna clase como target 
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
duracion_encoder = le.fit_transform(y)
duracion_encoder

array([14, 23, 29, 34, 36, 39, 40, 42, 43, 45, 47, 51, 53, 60, 61,  2, 11,
        9, 15, 58, 62,  5,  0,  9, 14, 16, 18, 20, 22, 24, 27, 28, 30, 31,
       32, 33, 35, 37, 38, 41, 44, 46, 48, 49, 50, 52, 54, 55, 56, 57, 59,
        3,  4,  6,  7,  8, 10, 12, 13, 21, 25, 26,  1, 21, 25, 26,  1, 17,
       18, 17, 18, 18, 18, 18, 17, 18, 19, 18, 18, 17, 17, 18, 18, 18, 17,
       17, 19, 17, 18, 17, 17, 19, 18, 19, 17, 18, 19, 18, 17, 17, 17, 19,
       17, 17, 18, 19, 19, 17, 19, 17, 17, 17, 19, 18, 18, 18, 18, 17, 18,
       19, 17, 19, 18, 17, 19, 19, 18, 19, 19, 18], dtype=int64)

In [28]:
y = np.array(duracion_encoder)
y.shape

(130,)

In [19]:
model = linear_model.LogisticRegression()
model

LogisticRegression()

In [50]:
model.fit(X,y)

LogisticRegression()

In [51]:
model.score(X, y)*100

100.0

In [52]:
predictions = model.predict(X)
print(predictions)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [59]:
seed= 10
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)

In [60]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(cv_results)
print(msg)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Logistic Regression: 1.000000 (0.000000)


In [65]:
predictions= model.predict(X_test)
predictions


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0,
       0, 2, 0, 0], dtype=int64)

In [62]:
model.score(X_test, y_test)* 100

100.0

In [57]:
# Con dos clases hay un porcentaje del 100% de acierto. 
acierto = accuracy_score(y_test, predictions)
error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 100.0 %
Error: 0.0 %


In [58]:
print(confusion_matrix(y_test, predictions))

[[23  0]
 [ 0  3]]
