### 1. 

En el archivo "logistic_regression_df_class" hemos visto un ejemplo multiclase. Elimina del dataframe todas las filas que se correspondan con la clase valor "1".

Ahora, realiza el ejercicio con el nuevo dataframe:

- ¿Se mejora la precisión del algoritmo con dos clases? ¿por qué?

LogisticRegression() es una clase que tiene varios parámetros de entrada. Investiga (modifica, prueba) los argumentos y comenta si modificando algunas de ellas se mejora el porcentaje de acierto del problema.

https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html


In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline
dataframe = pd.read_csv("../data/usuarios_win_mac_lin.csv")
dataframe.head()

duracion  paginas  acciones  valor  clase
0       7.0        2         4      8      2
1      21.0        2         6      6      2
2      57.0        2         4      4      2
3     101.0        3         6     12      2
4     109.0        2         6     12      2

In [3]:
df= dataframe[dataframe.clase != 1]
df

duracion  paginas  acciones  valor  clase
0         7.0        2         4      8      2
1        21.0        2         6      6      2
2        57.0        2         4      4      2
3       101.0        3         6     12      2
4       109.0        2         6     12      2
..        ...      ...       ...    ...    ...
165      13.0        1         7     42      0
166      12.0        1         2      6      0
167      13.0        1         3      9      0
168      13.0        1         7     28      0
169      12.0        1         6     18      0

[130 rows x 5 columns]

In [5]:
X = np.array(df.drop(['duracion'], axis=1))
y = np.array(df['clase'])
X.shape

(130, 4)

In [6]:
model = linear_model.LogisticRegression()
model

LogisticRegression()

In [7]:
model.fit(X,y)

LogisticRegression()

In [8]:
model.score(X, y)*100

100.0

In [10]:
seed= 10
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.2, random_state=seed)

In [11]:
predictions= model.predict(X_test)
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0,
       0, 2, 0, 0], dtype=int64)

In [12]:
model.score(X_test, y_test)*100

100.0

In [13]:
name='Logistic Regression'
kfold = model_selection.KFold(n_splits=10) #Parte los datos en 10 trozos para usar validación cruzada / cross validation
cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy')
msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
print(cv_results)
print(msg)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Logistic Regression: 1.000000 (0.000000)


In [65]:
predictions= model.predict(X_test)
predictions


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 2, 0, 2, 0,
       0, 2, 0, 0], dtype=int64)

In [62]:
model.score(X_test, y_test)* 100

100.0

In [57]:
# Con dos clases hay un porcentaje del 100% de acierto. 
# Con 3 clases daba un score de X_test e y_tes de : 0.8529411764705882
acierto = accuracy_score(y_test, predictions)
error = 1 - acierto
print("Acierto:", round(acierto*100, 2), "%")
print("Error:", round(error*100, 2), "%")

Acierto: 100.0 %
Error: 0.0 %


In [58]:
print(confusion_matrix(y_test, predictions))

[[23  0]
 [ 0  3]]
